require('dotenv').config();
const { FE_Document, SalesOrder, Customer, SalesOrderItem, Product, Company } = require('./models');
const DigifactAdapter = require('./services/fepa/adapters/DigifactAdapter');

async function run() {
    try {
        const orderId = 58; // From DB it is 58
        const companyId = 1;

        const order = await SalesOrder.findOne({
            where: { orderNumber: 'F - 2026 - 0058', companyId },
            include: [
                { model: Customer, as: 'customer' },
                { model: SalesOrderItem, as: 'items' }
            ]
        });

        if (!order) {
            console.log('Order not found');
            process.exit(1);
        }

        const items = order.items || [];

        const docData = {
            documentNumber: order.orderNumber,
            docType: '01', // Factura
            issueDate: new Date(),
            items: items.map(i => ({
                description: i.description,
                quantity: parseFloat(i.quantity),
                price: parseFloat(i.unitPrice),
                discount: parseFloat(i.discount) || 0,
                total: parseFloat(i.total),
                taxRate: parseFloat(i.taxRate) || 0,
                uom: i.uom || 'ud'
            })),
            customer: order.customer.toJSON(),
            documentNumber: order.orderNumber // Incluir el número original para AI04
        };

        const providerConfig = {
            environment: 'TEST',
            ruc: '155704849-2-2021', dv: '32', sucursal: '0000',
            authData: { user: 'PA.155704849-2-2021.CBAILEY', password: 'Digifact*25' },
            razonSocial: 'CBTECH CONSULTING', direccion: 'Direccion test',
            corregimiento: 'Corregimiento test', distrito: 'Distrito test',
            provincia: 'Provincia test', telefono: '6000-0000',
            coordenadas: '+8.9892,-79.5201', codUbi: '1-1-1'
        };

        const adapter = new DigifactAdapter(providerConfig);
        
        console.log('\n--- NUC JSON GENERATED BY CONTROLLER LOGIC ---');
        const nucJson = adapter.mapToNucJson(docData);
        console.log(JSON.stringify(nucJson, null, 2));

        console.log('\n--- SENDING TO DIGIFACT ---');
        const result = await adapter.signAndSend(docData);
        console.log(JSON.stringify(result, null, 2));

    } catch (error) {
        console.error("Error:", error);
    } finally {
        process.exit(0);
    }
}
run();
